### PR TITLE
Friendly error message for users with special characters in user names on Windows

### LINKED ISSUE #199: installation failled with accent in user name
I am trying to help two students who failed to install Conda.jl. A manual miniconda installation to the directory `c:\users\<username>\.julia\conda\3\` also failed. We see the following error in the miniconda installation log:

```
Traceback (most recent call last):
   File "concurrent\futures\process.py", line 368, in
_queue_management_worker
   File "multiprocessing\connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
```

Both students have a French accent in their username which seems to be an issue for conda (at least [anaconda](https://docs.anaconda.com/anaconda/user-guide/faq/)):

> We recommend installing Anaconda or Miniconda into a directory that contains only 7-bit ASCII characters and no spaces, such as C:\anaconda. Do not install into paths that contain spaces such as C:\Program Files or that include Unicode characters outside the 7-bit ASCII character set. This helps ensure correct operation and no errors when using any open-source tools in either Python 3 or Python 2 conda environments.

Could `Conda.jl` detect this issue and propose a work-around to the users?
I cannot replicate the issue locally, but after reading [build.jl](https://github.com/JuliaPy/Conda.jl/blob/e5444efa5d830c6e85f37e61775d6f19f91f2f8c/deps/build.jl) it seems that setting `ENV["CONDA_JL_HOME"]`  might be sufficient. 

See also https://github.com/conda/conda/issues/10239

### PR DESCRIPTION
**Pull request by Alexander-Barth**
This PR closes #199

### CODE REVIEW

File: deps/build.jl [hunk 1]
```diff
@@ -34,16 +34,30 @@ USE_MINIFORGE = lowercase(get(ENV, "CONDA_JL_USE_MINIFORGE", DefaultDeps.USE_MIN
...
+To leave Miniconda version as, it is unset the CONDA_JL_VERSION environment variable and rebuild.
+To change Miniconda version, you must delete the root environment and rebuild.
+WARNING: deleting the root environment will delete all the packages in it.
 This will break many Julia packages that have used Conda to install their dependancies.
 These will require rebuilding.
 """)
 end
 
+
+if Sys.iswindows() && (!isascii(ROOTENV) || ' ' ∈ ROOTENV)
```
Comment (stevengj) [inline deps/build.jl:48]: This shouldn't go here, it should go into `Conda._install_conda`, so that you only get an error (or a warning?) if you actually try to install Anaconda.

**Comment by Alexander-Barth** [comment]
I placed the error message `build.jl` to prevent the creation of `deps.jl` with an unusable `ROOTENV` and I chose an error (instead of a warning) because the current miniconda installer failed in all cases that I am aware of. But I did not try miniforge or any non-default locale settings/file systems. I have no strong opinion about this.

File: deps/build.jl (hunk 1 above)
Comment (Alexander-Barth) [reply deps/build.jl]: I agree, I updated the PR.

File: src/Conda.jl [hunk 2]
```diff
@@ -189,6 +189,21 @@ _quiet() = get(ENV, "CI", "false") == "true" ? `-q` : ``
 "Install miniconda if it hasn't been installed yet; _install_conda(true) installs Conda even if it has already been installed."
 function _install_conda(env::Environment, force::Bool=false)
     if force || !isfile(Conda.conda)
+        if Sys.iswindows() && (!isascii(PREFIX) || ' ' ∈ PREFIX)
```
Comment (stevengj) [inline src/Conda.jl:192]: Note that spaces in the path are not supported on any operating system, so it might be good to give an error in general in that case.

File: src/Conda.jl [hunk 3]
```diff
@@ -189,6 +189,21 @@ _quiet() = get(ENV, "CI", "false") == "true" ? `-q` : ``
...
+            error("""Conda.jl cannot be installed to its default location $(PREFIX) as
+Miniconda does not support the installation to a directory with a non-ASCII
+character or a space on Windows. The work-around is to install Miniconda to a
+user-writable directory by setting the CONDA_JL_HOME environment
+variable before installing Conda.jl. For example:
+
+ENV["CONDA_JL_HOME"] = "C:\\\\Conda-julia\\\\3"
```
Comment (stevengj) [inline src/Conda.jl:199]: Probably clearer to use `raw"C:\\Conda-Julia\3"`

Comment (stevengj) [reply src/Conda.jl:199]: (`\\\\` gives a double backslash; not sure why that would be needed?)

File: README.md [hunk 4]
```diff
@@ -133,6 +133,30 @@ pkg> build Conda
...
 
+
+## Troubleshooting
+
+### Installation on Windows with special characters in user names
+
+If you have a special character in your user name (like an umlaut, an accent or a space) the installation which defaults to
+directory `C:\Users\<username>\.julia\Conda\3` will fail on Windows.
+This is a [known issue](https://github.com/conda/conda/issues/10239). The work-around is to install Miniconda to a user-writable directory outside of the home directory.
+If you have an unsuccessful installation of `Conda.jl` and/or related packages like `IJulia` or `PyPlot`, it might be necessary to remove these packages first.
```
Comment (stevengj) [inline README.md:144]: That shouldn't be necessary.

File: README.md [hunk 5]
```diff
@@ -133,6 +133,30 @@ pkg> build Conda
...
+Before installing `Conda.jl`, choose a directory without space and without special characters and set the environment variable `CONDA_JL_HOME` as follows inside a julia session:
+
+```julia
+ENV["CONDA_JL_HOME"] = "C:\\Conda-julia\\3"
+
+# Install Conda.jl
+using Pkg
+Pkg.add("Conda")
```
Comment (stevengj) [inline README.md:152]: If they have already added Conda (which seems likely if they are troubleshooting), they should use `Pkg.build` here.

File: README.md (hunk 4 above)
Comment (stevengj) [reply README.md:144]: (It should be sufficient to re-build IJulia and PyCall.)

File: src/Conda.jl [hunk 6]
```diff
@@ -189,6 +189,21 @@ _quiet() = get(ENV, "CI", "false") == "true" ? `-q` : ``
...
+using Pkg
+Pkg.rebuild("Conda")
```
Comment (stevengj) [inline src/Conda.jl:201]: build, not rebuild.

Comment (stevengj) [reply src/Conda.jl:201]: Note that they will need to restart Julia before or after this (i.e. before they try using Conda again)

File: src/Conda.jl (hunk 3 above)
Comment (Alexander-Barth) [reply src/Conda.jl:199]: The idea would be that the user would just need to copy and paste the command. The error message would either print-out a double backslash or use `raw"C:\Conda-Julia\3"` (I use the latter in the updated PR).

**Comment by Alexander-Barth** [comment]
Thank you very much for your feed-back. I just updated the PR. With the revised PR, the error message now reads:

```
ERROR: Conda.jl cannot be installed to its default location C:\Users\Clément\.julia\conda\3
as Miniconda does not support the installation to a directory with a space or a
non-ASCII character on Windows. The work-around is to install Miniconda to a
user-writable directory by setting the CONDA_JL_HOME environment variable. For
example on Windows:

ENV["CONDA_JL_HOME"] = raw"C:\Conda-Julia\3"
using Pkg
Pkg.build("Conda")

The Julia session need to be restarted. More information is available at
https://github.com/JuliaPy/Conda.jl.
```

**Comment by Alexander-Barth** [comment]
I am wondering if this PR can be merged now. Should I rebase it?

**Comment by mkitti** [comment]
Hmm, if you rebase I will merge.

**Comment by Alexander-Barth** [comment]
I just rebased the PR. I now see this failure on windows:

```
[ Info: Running `conda create -q -y -p 'C:\Users\runneradmin\.julia\conda\3\x86_64\envs\test_conda_jl'` in root environment
...
 File "C:\Users\runneradmin\.julia\conda\3\x86_64\lib\site-packages\urllib3\_request_methods.py", line 10, in <module>
    from .response import BaseHTTPResponse
  File "C:\Users\runneradmin\.julia\conda\3\x86_64\lib\site-packages\urllib3\response.py", line 282, in <module>
    class BaseHTTPResponse(io.IOBase):
  File "C:\Users\runneradmin\.julia\conda\3\x86_64\lib\site-packages\urllib3\response.py", line 292, in BaseHTTPResponse
    DECODER_ERROR_CLASSES += (brotli.error,)
AttributeError: module 'brotli' has no attribute 'error'
```

This seems to be a known conda issue:
https://github.com/conda/conda/issues/9903

**Review by stevengj — APPROVED** [review]

**Comment by mkitti** [comment]
I encountered the same issue earlier.
